In [1]:
import numpy as np

In [3]:
#Creación de listas para dps concatenarlas
x = [1,2,3]
y = [1,2,3]
z = [1,2,3]

In [4]:
#Concatenación de una lista mediaante la fn .concatenate() de numpy
np.concatenate([x,y,z])#Esto devolverá un solo array, por el hecho de que lo hicimos con numpy

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [15]:
#Concatenamos con el valor del param axis en 1
a = [[1,2]
    ,[3,4]]

b = [[5,6],
    [7,8]]

np.concatenate([a,b],axis = 1 )

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [17]:
np.concatenate([a,b],axis = 0 )

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [18]:
#Concatenamos con el valor del param axis en 0
array_concatenado = np.concatenate([a,b],axis = 0)
array_concatenado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
array_concatenado.shape

(4, 2)

In [20]:
#Reformar nuestro array, que quede igual como con el axis = 1 la forma pero con el orden del axis = 0
array_reformado = array_concatenado.reshape(2,4)
array_reformado

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
#Sumamos dos mismos arrays
array_suamdo = array_reformado +  array_reformado
array_suamdo

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [24]:
#Multiplicamos dos mismos arrays
array_multipli = array_reformado *  array_reformado
array_multipli

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [26]:
#Calculos de la raíz cudrada en un array con la fn sqrt() de numpy
raices = np.sqrt(array_multipli)
raices

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])