In [2]:
import numpy as np

In [3]:
array1d = np.array([1,2,3,4,5])

In [4]:
array2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [5]:
array1d[0]#Acceso al primer elemento del array

np.int64(1)

In [6]:
array1d[-1]#Acá al ser - llegamos al ult elemento del array

np.int64(5)

In [7]:
array2d[0]#Así al ser bidimensional no accedemos al elemento, sino q accedemos a la primer fila pq el array2d está compuesta por filas y las filas por elementos todo esto pq es bidimensional

array([1, 2, 3])

Acceso a un ínidice específico de un array bidimensional

In [8]:
array2d[1][2]#Así accedo al índice osea el número específico del elemento-fila 1. El 1er [] marca el elemento y 2do [] el índice

np.int64(6)

In [9]:
array2d[1,2]#Esto es lo mismo que el de arriba, da lo mismo pero hecho de otra forma

np.int64(6)

Slincing

In [10]:
array1d[1:4]#Accedemos de tal índice a tal otro de esta forma, desde el uno hasta el cuatro, pero hay que decir que el ult numero nunca se incluye osea el 4

array([2, 3, 4])

Slicing para arrays bidimensionales

In [18]:
array2d[1, :]#Así accedo al todos los ínidices del elemento 1, pq a todos?? pq al ponero dps del 1 los dos : quiere decir que quiero acceder a todos

array([4, 5, 6])

In [19]:
array2d[1, 0:2]#Esto es similar al anterior pero acá solo accedemos a los dos 1eros indices

array([4, 5])

Slicing para obtener una columna completa

In [23]:
array2d[:,1]#Estamos accediendo  a la columna entera gracias a los : y dps específicamos q índices queremos tomar de esa columna-conj de elementos

array([[1, 2],
       [4, 5],
       [7, 8]])

In [26]:
array2d[:,1:3]#Lo mismo que el anterior pero... aca accedemos a más de un índice

array([[2, 3],
       [5, 6],
       [8, 9]])

In [24]:
array2d[:2,:2]#Acá accedemos desde el elemento 0 hasta el 1(acrdate que el ult num no incluye) y a los ínidices desde el 0 hasta el 1

array([[1, 2],
       [4, 5]])

Indexacion booleana:permite seleccionar elementos de un arrays segun la cond que le demos 

In [27]:
array1d > 3#Esto dev el array pero modif los valores y diciendo cuales cumple la cond y cuales no representados en valores booleanos

array([False, False, False,  True,  True])

In [28]:
array2d  % 2 == 0#Acá tb le pasamos una cond diciendo que si es par dev los valores booleanos True o False dependiendo de quien sea par o no  

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])