In [1]:
import numpy as np

In [2]:
array = np.array([1,2,3,4,5,6,7,8,9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
array.shape#Obtendremos que tiene 9 de largo pq es un array unidimensional

(9,)

In [5]:
arra_mod = array.reshape(3,3)#Lo reestructuramos haciendo que tenga 3 elementos con 3 índices en cada uno gracias a .reashape()
arra_mod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
arra_mod2 = array.reshape(-1,3)#Esto dará lo mismo que el de arriba nada mas que ese -1 lo que hace es que numpy calc las filas automáticammente pero para usarlo el array debe de tener un numero de elementos divisible por 3 para evitar errores
arra_mod2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Transpose:metodo que voltea el array, cambia filas -> a columnas y column -> filas

In [9]:
array_volteado = arra_mod2.transpose()
array_volteado#veremos que las filas pasan de horizont a vertical

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Conv un array multidimensional a uno unidimensional

In [10]:
array_chato = arra_mod.flatten()#Mediante el met flatten conv a uno unidimensional y crea una copia aplanada del array lo que hace que ocupe lugar en memoria
array_chato

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array_chato = arra_mod.ravel()#Mediante el met ravel conv a uno unidimensional pero no crea copia este, sino que crea una vista aplanada  del array original
array_chato

array([1, 2, 3, 4, 5, 6, 7, 8, 9])