In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
array2 = np.array(
                   [[0]
                   ,[10]
                   ,[20]
                   ,[30]]
)

array2

array([[ 0],
       [10],
       [20],
       [30]])

Operacion de suma con dos arrays de distintas formas, uno es unidimensional y el otro es bidimensional, esto se denomina como fenómeno broadcasting

In [5]:
broadcast_suma = array2 + array1
broadcast_suma#Acá lo que sucede es que el array1 que es unidimensional se sumará con el array2 que es bidimensional, pero esto:[1,2,3] este array se sumará a [0],[10],[20],[30] con cada uno de estos arrays específicamente con sus elementos interno, por ende tendriamos algo asi: 0+1,0+2,0+3=[1,2,3], 10+1,10+2,10+3=[11,12,13] y asi... con todos los elementos del array 

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [6]:
broadcast_multiplic = array2 * array1
broadcast_multiplic#Acá se produce lo mismo que arriba

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

Funciones universales en Numpy(UFUNC)

In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [17]:
resultado = np.add(a,b)
resultado#Acá obtendremos una suma de elemento por elemento de acuerdo a la posicion de cada uno: 1+4,2+5,3+6 y esto gracias a la fn de numpy a

array([5, 7, 9])

In [19]:
resultado = np.subtract(a,b)
resultado#Acá sucederá lo mismo pero estamos restando

array([-3, -3, -3])

In [20]:
resultado = np.multiply(a,b)
resultado#Acá sucederá lo mismo pero estamos multiplicando

array([ 4, 10, 18])

In [21]:
resultado = np.divide(a,b)
resultado#Acá sucederá lo mismo pero estamos dividiendo

array([0.25, 0.4 , 0.5 ])

Exponencial

In [26]:
#Asi hacemos el exponencial gracias a la fn .exp()
resultado2 = np.exp(a)
resultado2

array([ 2.71828183,  7.3890561 , 20.08553692])

In [ ]:
Logarítmo

In [34]:
resultado3 = np.log(a)
resultado3

array([0.        , 0.69314718, 1.09861229])

In [30]:
resultado3 = np.log10(a)#Le podemos meter la base tb, ej:log2(),log10()....
resultado3

array([0.        , 0.30103   , 0.47712125])

Raíz cuadrada

In [32]:
resultado5 = np.sqrt(a)#sqrt() es la fn para obtener la raíz cuadrada
resultado5

array([1.        , 1.41421356, 1.73205081])

Hay mas cosas para ver sobre ufunc ya que hay muchísimas fns mas que se usan lo mejor es verlas y repasarlas en el cuaderno de JN del día 8