In [1]:
import numpy as np

In [2]:
#Creamos un array con un nan apropósito
array = np.array([1,2,np.nan,4,5])#Así le metemos el nan, con el .nan 
array

array([ 1.,  2., nan,  4.,  5.])

Comporbacion de si en un array hay un valor no válido osea un nan 

In [3]:
np.isnan(array)#Nos dev cono valores booleanos, si el falso no hay y si es True sí hay un nan

array([False, False,  True, False, False])

Cálculos con valores nan de por medio en un array... 

In [4]:
np.mean(array)#Si quisieramos calc el promedio de los núm que están en el array y hay un nan obtendremos esto... un num no válido

np.float64(nan)

In [5]:
np.nanmean(array)#Pero.... lo bueno de numpy es que tiene estas cosas... podemos calc el promedio de un array con un valor nan de por medio usando el método .nanmean de la librería np 

np.float64(3.0)

En la carp de día 8 hay cuaderno de JN en el cúal están o hay un listado de las fnes faltantes

fn .where():lo que hace es pasar por cada elemento dela array,osea iterarlo,preguntandose si ahi donde se cumpla una determinada  vamos hacer una cosa y si no se cumple hacemos otra cosa. Es una mezcla entre un for y un if

In [6]:
array_con_0 = np.where(np.isnan(array),0,array)#Acá lo que hacemos es que si en el array original encuentra un un elemento igual a nan tiene q reemplazarlo por 0, de lo contrario si no es nan y es número un random por ej tiene que dejar ese número ahí como está. Por ende primero pusimos la cond, dps lo que tiene que hacer si se cumple esa misma y dps lo tiene que hacer si no se cumple esa cond 
array_con_0

array([1., 2., 0., 4., 5.])

In [13]:
promedio = np.nanmean(array)
promedio_reemplazo =  np.where(np.isnan(array),promedio,array)#Acá estamos reemplazando tb los nan pero ahora por el promedio que nos dio de todo el array entero, es decir si al iterar encuentra en el array el-los nan que los reemplace por el promdio que calc con la fn .mean()
promedio_reemplazo

array([1., 2., 3., 4., 5.])

In [ ]:
Eliminar un dato faltante en un array con ~

In [18]:
array_filtrado = array[~np.isnan(array)]#A ver.... si esto lo realizo sin ~ voy a obtener solo el nan, cuando lo pongo obtengo lo contrario ya que esto niega todo y obtendría todos los número del array menos el valor nan
array_filtrado

array([1., 2., 4., 5.])